name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Use the correct version for your project

    - name: Restore all projects
      run: |
        for proj in $(find . -name "*.csproj"); do
        dotnet restore "$proj"
        done

    - name: Build all projects
      run: |
        for proj in $(find . -name "*.csproj"); do
        dotnet build "$proj" --configuration Release --no-restore
        done  

    - name: Pack Prober
      run: dotnet pack ./RP.Prober/RP.Prober.csproj --configuration Release --output ./nupkgs

    - name: Pack Prober Razor Component
      run: dotnet pack ./RP.Prober.Razor.Component/RP.Prober.Razor.Component.csproj --configuration Release --output ./nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
